### ISSUE TITLE
Find best way to expand execution engine to accommodate more intermediate steps

### ISSUE THREAD

**Issue by Skrinikov** [insufficiently-caffeinated/caffeine#196]
We need to add some non-symbolic-execution steps to the program that would allow us to optimize its runtime. 
The goal of this issue is to figure out what changes - if any - are needed to be made to the interpreter/executor.

Few steps that we should be able to add:
- Pre-symbolic stuff. e.g. static analysis, branch graph creation, (this is probably already here, just find a way to make it cleaner)
- Post context exit (i.e. a path reached program termination or an error state, we want to run some stuff afterwards)
- Pre-branch creation. (e.g. verify if this branch is worth creating)

Expected outcome:
 - new issue outlining concrete stuff that needs to be changed in the current code

**Comment by Skrinikov** [comment]
@Phantomical Any opinions on this issue? You probably have more context on what is currently available and what is not

**Comment by Phantomical** [comment]
> Any opinions on this issue?

This looks good! Actually making it work is probably going to require a bit of a redesign of the interpreter but it's been getting pretty unwieldy now anyways so I think doing that sort of redesign is likely to be a good idea anyway. I'm not sure as to the details for what's worth doing here but I definitely agree that it's worth looking into.

**Comment by Phantomical** [comment]
Closing this as I think this is mostly complete at this point. If we need more changes that can be done under a new issue.
