### ISSUE TITLE
Modify how `logFailure` handles assertions

### ISSUE THREAD

**Issue by mishazharov** [insufficiently-caffeinated/caffeine#401]
Currently we don't pass all the assertions needed to create an accurate model to the `logFailure` method. For instance: https://github.com/insufficiently-caffeinated/caffeine/blob/737bb4e4f6cc0b74735ad7255c3f0d4f8f59d58c/src/Interpreter/Interpreter.cpp#L162

The `Context` passed to `logFailure` doesn't contain the assertion that the denominator is 0, so when we go to create a model of it, the denominator won't necessarily be 0.

As a fix, we can copy the `Context`, add the new assertions, and pass it into `logFailure`, and discard it after that.

**Comment by Phantomical** [comment]
Just as note, it's probably more helpful to go about this the other way: Both the `check` and `resolve` methods of `Solver` allow you to pass in an extra assertion. So it's easier for the default to be "we have this extra assertion that's not in the list" and then if you don't you can just set the extra assertion to a constant `true`.
