### ISSUE TITLE
Implement Bitcast instruction.

### ISSUE THREAD

**Issue by Phantomical** [insufficiently-caffeinated/caffeine#49]
This is needed to support memory operations.

Note that bitcast is different from LLVM's bitcast. It's meant for bitwise casting between floating point and integer values. (We don't have pointers as part of our IR so LLVM's bitcast wouldn't make sense)

**Comment by mishazharov** [comment]
I've implemented ZExt, SExt, Trunc. Can you please add more info on bitcasting?

**Comment by Phantomical** [comment]
@mishazharov Basically bitcast is a bitwise cast between integers and equivalently-sized floating point types (and the other way as well).

It should have equivalent behaviour to doing
```c
float x;
uint32_t y;
std::memcpy(&y, &x, sizeof(x));
```
that is to say that it should just move the bits from one type to another.

**Comment by Phantomical** [comment]
Some more notes:
- The bitcast operation in LLVM is just used to convert between different pointer types (to the best of my knowledge). We only have one pointer type so this doesn't translate to anything on our end. In the interpreter it can probably be implemented as a pass-through.
- The bitcast expression is used as part of reading and writing memory. You can see what it's used for by looking at `Allocation::read` and `Allocation::write` in `MemHeap.cpp`.

Feel free to rename the instruction to a clearer name if you think `bitcast` is too confusing given that LLVM's bitcast has different semantics.

**Comment by mishazharov** [comment]
Awesome, thanks. I'll take another look at this when it gets less crazy
