### ISSUE TITLE
Model external functions properly

### ISSUE THREAD

**Issue by mishazharov** [insufficiently-caffeinated/caffeine#501]
Currently when we implement external functions we do not model stack frames properly. As a result, external functions cannot call other functions and get their return value because the callee has nowhere to return its results (it would instead insert it into the last real frame that's on the stack).

To fix this, I propose:
* We add an enum field for stackframes in order to tell external stackframes vs internal ones (I suspect this will make libunwind's implementation easier)
* Make extern functions create special extern stack frames
* Use this to implement complex extern functions which call other functions

**Comment by Phantomical** [comment]
@mishazharov I think this was mostly addressed by #504?
