### ISSUE TITLE
Show progress output from caffeine while running

### ISSUE THREAD

**Issue by Phantomical** [insufficiently-caffeinated/caffeine#507]
# Motivation
Right now when caffeine is running we have no output unless we find an assertion failure or we hit an internal error. This isn't very helpful for users since it's rather hard to tell the difference between caffeine being hung and it just not having completed yet.

# Requirements
These aren't exact but give the general idea:
- It should show `number of contexts completed/total number of contexts`
- It should be updated whenever those ones above change

I'm leaving this mostly open but it should show basically `number of contexts completed/total number of contexts`.

One you have the basic thing working an extra bonus feature would be if it didn't always print the status on a newline and instead showed it as a status bar at the bottom of the terminal similar to what `apt` does.

# Implementations
This should either be a wrapper around an `ExecutionContextStore` or an `ExecutionPolicy`. I'll leave it to you to figure out which one you think is best.

**Comment by mishazharov** [comment]
Closed by https://github.com/insufficiently-caffeinated/caffeine/pull/576
