### ISSUE TITLE
Investigate integrating with libfuzzer / afl++

### ISSUE THREAD

**Issue by Phantomical** [insufficiently-caffeinated/caffeine#88]
We'd like to be able to integrate caffeine into libfuzzer and also for applications that already use libfuzzer to be able to (somewhat) easily plug in caffeine to their existing test suites. (or, more realistically, for us to run caffeine on their existing test suites).

There's two different things that this issue encompasses:
1. What do we need to do so that we can run caffeine on existing libFuzzer test harnesses with little to no modification to the test harness.
2. How might we go about integrating caffeine into libFuzzer so that it can be used to direct fuzzing efforts. This will most likely be based on the work in the first item but will involve a lot more changes to caffeine itself. This is the hybrid fuzzing idea suggested by Prof Arie

Ideally someone could document what's probably needed to accomplish each of and then we can start working on them.

**Comment by mishazharov** [comment]
Depends on #318
